Destination.create(name: "Viejo Vallarta", description_title: "Bienvenido a unas vacaciones llenas de lujo")
Destination.create(name: "Riviera Otomí", description_title: "Un mundo selvático lleno de lujo")
Destination.create(name: "Las Playas", description_title: "El lujoso destino de moda en México")
Destination.create(name: "Puerto Montaña", description_title: "Descubra un mundo como ninguno otro")
Destination.create(name: "Puerto Durazo", description_title: "El corazón de México")
