Destination.create(name: "Viejo Vallarta")
Destination.create(name: "Riviera Otomí")
Destination.create(name: "Las Playas")
Destination.create(name: "Puerto Montaña")
Destination.create(name: "Puerto Durazo")
